// --- Created by Jason McRay ---

import mods.gregtech.Autoclave;
import mods.gregtech.ChemicalReactor;

# Aliases
// Combs
var combAluminium           = <gendustry:HoneyComb:131>;	
var combCertus              = <gendustry:HoneyComb:112>;	
var combChrome              = <gendustry:HoneyComb:134>;	
var combCoal	            = <gendustry:HoneyComb:102>;
var combCopper              = <gendustry:HoneyComb:122>;	
var combDiamond             = <gendustry:HoneyComb:118>;	
var combEmerald             = <gendustry:HoneyComb:120>;	
var combGold                = <gendustry:HoneyComb:130>;	
var combIridium             = <gendustry:HoneyComb:137>;	
var combIron                = <gendustry:HoneyComb:125>;	
var combLapis               = <gendustry:HoneyComb:115>;	
var combLead                = <gendustry:HoneyComb:124>;	
var combLignite	            = <gendustry:HoneyComb:101>;
var combManganese           = <gendustry:HoneyComb:132>;	
var combNaquadah            = <gendustry:HoneyComb:140>;	
var combNickel              = <gendustry:HoneyComb:127>;	
var combOil	                = <gendustry:HoneyComb:104>;
var combOlivine             = <gendustry:HoneyComb:119>;	
var combPlatinum            = <gendustry:HoneyComb:136>;	
var combPlutonium           = <gendustry:HoneyComb:139>;	
var combRedstone            = <gendustry:HoneyComb:114>;	
var combRuby                = <gendustry:HoneyComb:116>;	
var combSapphire            = <gendustry:HoneyComb:117>;	
var combSilver              = <gendustry:HoneyComb:129>;	
var combSlag	            = <gendustry:HoneyComb:121>;
var combSteel	            = <gendustry:HoneyComb:126>;
var combStone	            = <gendustry:HoneyComb:111>;
var combTin                 = <gendustry:HoneyComb:123>;	
var combTitanium            = <gendustry:HoneyComb:133>;	
var combTungsten            = <gendustry:HoneyComb:135>;	
var combUranium238          = <gendustry:HoneyComb:138>;	
var combZinc                = <gendustry:HoneyComb:128>;	


// Liquids
var UUM                     = <liquid:ic2uumatter>;	
var water                   = <liquid:water>;	
var moltenAluminium         = <liquid:molten.aluminium>;	
var moltenAntimony	        = <liquid:molten.antimony>;
var moltenBeryllium         = <liquid:molten.beryllium>;	
var moltenCarbon	        = <liquid:molten.carbon>;
var moltenChrome            = <liquid:molten.chrome>;	
var moltenCobalt            = <liquid:molten.cobalt>;	
var moltenCopper            = <liquid:molten.copper>;	
var moltenIridium	        = <liquid:molten.iridium>;
var moltenIron              = <liquid:molten.iron>;	
var moltenLead              = <liquid:molten.lead>;	
var moltenLithium	        = <liquid:molten.lithium>;
var moltenMagnesium	        = <liquid:molten.magnesium>;
var moltenManganese         = <liquid:molten.manganese>;	
var moltenMolybdenum	    = <liquid:molten.molybdenum>;
var moltenNaquadah	        = <liquid:molten.naquadah>;
var moltenNaquadahEnriched  = <liquid:molten.naquadahenriched>;	
var moltenNeodymium	        = <liquid:molten.neodymium>;
var moltenNickel            = <liquid:molten.nickel>;	
var moltenPalladium	        = <liquid:molten.palladium>;
var moltenPlatinum          = <liquid:molten.platinum>;	
var moltenRedstone	        = <liquid:molten.redstone>;
var moltenSilver            = <liquid:molten.silver>;	
var moltenThorium	        = <liquid:molten.thorium>;
var moltenTin               = <liquid:molten.tin>;	
var moltenUranium238        = <liquid:molten.uranium>;	


// Purified Ores
var purifiedAlmandine	    = <gregtech:gt.metaitem.01:6820>;
var purifiedAluminium       = <gregtech:gt.metaitem.01:6019>;	
var purifiedApatite	        = <gregtech:gt.metaitem.01:6530>;
var purifiedBandedIron	    = <gregtech:gt.metaitem.01:6917>;
var purifiedBarite	        = <gregtech:gt.metaitem.01:6904>;
var purifiedBastnasite	    = <gregtech:gt.metaitem.01:6905>;
var purifiedBauxite	        = <gregtech:gt.metaitem.01:6822>;
var purifiedBentonite	    = <gregtech:gt.metaitem.01:6927>;
var purifiedBeryllium	    = <gregtech:gt.metaitem.01:6008>;
var purifiedBLimonite	    = <gregtech:gt.metaitem.01:6930>;
var purifiedCalcite	        = <gregtech:gt.metaitem.01:6823>;
var purifiedCassiterite	    = <gregtech:gt.metaitem.01:6824>;
var purifiedCertus          = <gregtech:gt.metaitem.01:6516>;	
var purifiedChalcopyrite	= <gregtech:gt.metaitem.01:6855>;
var purifiedChrome          = <gregtech:gt.metaitem.01:6030>;	
var purifiedChromite	    = <gregtech:gt.metaitem.01:6825>;
var purifiedCinnabar	    = <gregtech:gt.metaitem.01:6826>;
var purifiedCoal	        = <gregtech:gt.metaitem.01:6535>;
var purifiedCobaltite	    = <gregtech:gt.metaitem.01:6827>;
var purifiedCopper          = <gregtech:gt.metaitem.01:6035>;	
var purifiedDiamond         = <gregtech:gt.metaitem.01:6500>;	
var purifiedEmerald         = <gregtech:gt.metaitem.01:6501>;	
var purifiedEnrichedNaq	    = <gregtech:gt.metaitem.01:6326>;
var purifiedGalena	        = <gregtech:gt.metaitem.01:6830>;
var purifiedGarnierite	    = <gregtech:gt.metaitem.01:6906>;
var purifiedGlauconite	    = <gregtech:gt.metaitem.01:6933>;
var purifiedGold            = <gregtech:gt.metaitem.01:6086>;	
var purifiedGraphite	    = <gregtech:gt.metaitem.01:6865>;
var purifiedGreenSapphire   = <gregtech:gt.metaitem.01:6504>;	
var purifiedGrossular	    = <gregtech:gt.metaitem.01:6831>;
var purifiedIlmenite        = <gregtech:gt.metaitem.01:6918>;	
var purifiedIridium         = <gregtech:gt.metaitem.01:6084>;	
var purifiedIron            = <gregtech:gt.metaitem.01:6032>;	
var purifiedLapis           = <gregtech:gt.metaitem.01:6526>;	
var purifiedLazurite	    = <gregtech:gt.metaitem.01:6524>;
var purifiedLead            = <gregtech:gt.metaitem.01:6089>;	
var purifiedLepidolite	    = <gregtech:gt.metaitem.01:6907>;
var purifiedLignite	        = <gregtech:gt.metaitem.01:6538>;
var purifiedLithium	        = <gregtech:gt.metaitem.01:6006>;
var purifiedMagnesite	    = <gregtech:gt.metaitem.01:6908>;
var purifiedMagnetite	    = <gregtech:gt.metaitem.01:6870>;
var purifiedMalachite	    = <gregtech:gt.metaitem.01:6871>;
var purifiedManganese       = <gregtech:gt.metaitem.01:6031>;	
var purifiedMeteoricIron	= <gregtech:gt.metaitem.01:6340>;
var purifiedMolybdenite	    = <gregtech:gt.metaitem.01:6942>;
var purifiedMolybdenum	    = <gregtech:gt.metaitem.01:6048>;
var purifiedMonazite	    = <gregtech:gt.metaitem.01:6520>;
var purifiedNaquadah        = <gregtech:gt.metaitem.01:6324>;	
var purifiedNaquadria	    = <gregtech:gt.metaitem.01:6327>;
var purifiedNeodymium	    = <gregtech:gt.metaitem.01:6067>;
var purifiedNickel          = <gregtech:gt.metaitem.01:6034>;	
var purifiedOilsands	    = <gregtech:gt.metaitem.01:6878>;
var purifiedOlivine         = <gregtech:gt.metaitem.01:6505>;	
var purifiedOsmium	        = <gregtech:gt.metaitem.01:6083>;
var purifiedPalladium	    = <gregtech:gt.metaitem.01:6052>;
var purifiedPentlandite	    = <gregtech:gt.metaitem.01:6909>;
var purifiedPhosphate	    = <gregtech:gt.metaitem.01:6833>;
var purifiedPhosphorus	    = <gregtech:gt.metaitem.01:6534>;
var purifiedPitchblende	    = <gregtech:gt.metaitem.01:6873>;
var purifiedPlatinum        = <gregtech:gt.metaitem.01:6085>;	
var purifiedPlutonium       = <gregtech:gt.metaitem.01:6100>;	
var purifiedPowellite	    = <gregtech:gt.metaitem.01:6883>;
var purifiedPyrite	        = <gregtech:gt.metaitem.01:6834>;
var purifiedPyrolusite	    = <gregtech:gt.metaitem.01:6943>;
var purifiedPyrope	        = <gregtech:gt.metaitem.01:6835>;
var purifiedQuartzite	    = <gregtech:gt.metaitem.01:6523>;
var purifiedRedstone        = <gregtech:gt.metaitem.01:6810>;	
var purifiedRockSalt	    = <gregtech:gt.metaitem.01:6944>;
var purifiedRuby            = <gregtech:gt.metaitem.01:6502>;	
var purifiedSalt	        = <gregtech:gt.metaitem.01:6817>;
var purifiedSapphire        = <gregtech:gt.metaitem.01:6503>;	
var purifiedScheelite	    = <gregtech:gt.metaitem.01:6910>;
var purifiedSheldonite	    = <gregtech:gt.metaitem.01:6828>;
var purifiedSilver          = <gregtech:gt.metaitem.01:6054>;	
var purifiedSoapstone	    = <gregtech:gt.metaitem.01:6877>;
var purifiedSodalite	    = <gregtech:gt.metaitem.01:6525>;
var purifiedSpessartine	    = <gregtech:gt.metaitem.01:6838>;
var purifiedSphalerite	    = <gregtech:gt.metaitem.01:6839>;
var purifiedSpodumene	    = <gregtech:gt.metaitem.01:6920>;
var purifiedStibnite	    = <gregtech:gt.metaitem.01:6945>;
var purifiedSulfur	        = <gregtech:gt.metaitem.01:6022>;
var purifiedTalc	        = <gregtech:gt.metaitem.01:6902>;
var purifiedTantalite	    = <gregtech:gt.metaitem.01:6921>;
var purifiedTetrahedrite	= <gregtech:gt.metaitem.01:6840>;
var purifiedThorium	        = <gregtech:gt.metaitem.01:6096>;
var purifiedTin             = <gregtech:gt.metaitem.01:6057>;	
var purifiedTitanium	    = <gregtech:gt.metaitem.01:6028>;
var purifiedTungstate       = <gregtech:gt.metaitem.01:6841>;	
var purifiedUraninite	    = <gregtech:gt.metaitem.01:6922>;
var purifiedUranium235	    = <gregtech:gt.metaitem.01:6097>;
var purifiedUranium238      = <gregtech:gt.metaitem.01:6098>;	
var purifiedVanMagnetite	= <gregtech:gt.metaitem.01:6923>;
var purifiedWulfenite	    = <gregtech:gt.metaitem.01:6882>;
var purifiedYLimonite	    = <gregtech:gt.metaitem.01:6931>;
var purifiedZinc            = <gregtech:gt.metaitem.01:6036>;	


// Crushed Ores
var crushedAlmandine	    = <gregtech:gt.metaitem.01:5820>;
var crushedAluminium        = <gregtech:gt.metaitem.01:5019>;	
var crushedApatite	        = <gregtech:gt.metaitem.01:5530>;
var crushedBandedIron	    = <gregtech:gt.metaitem.01:5917>;
var crushedBarite	        = <gregtech:gt.metaitem.01:5904>;
var crushedBastnasite	    = <gregtech:gt.metaitem.01:5905>;
var crushedBauxite	        = <gregtech:gt.metaitem.01:5822>;
var crushedBentonite	    = <gregtech:gt.metaitem.01:5927>;
var crushedBeryllium	    = <gregtech:gt.metaitem.01:5008>;
var crushedBLimonite	    = <gregtech:gt.metaitem.01:5930>;
var crushedCalcite	        = <gregtech:gt.metaitem.01:5823>;
var crushedCassiterite	    = <gregtech:gt.metaitem.01:5824>;
var crushedCertus           = <gregtech:gt.metaitem.01:5516>;	
var crushedChalcopyrite	    = <gregtech:gt.metaitem.01:5855>;
var crushedChrome           = <gregtech:gt.metaitem.01:5030>;	
var crushedChromite	        = <gregtech:gt.metaitem.01:5825>;
var crushedCinnabar	        = <gregtech:gt.metaitem.01:5826>;
var crushedCoal	            = <gregtech:gt.metaitem.01:5535>;
var crushedCobaltite	    = <gregtech:gt.metaitem.01:5827>;
var crushedCopper           = <gregtech:gt.metaitem.01:5035>;	
var crushedDiamond          = <gregtech:gt.metaitem.01:5500>;	
var crushedEmerald          = <gregtech:gt.metaitem.01:5501>;	
var crushedEnrichedNaq	    = <gregtech:gt.metaitem.01:5326>;
var crushedGalena	        = <gregtech:gt.metaitem.01:5830>;
var crushedGarnierite	    = <gregtech:gt.metaitem.01:5906>;
var crushedGlauconite	    = <gregtech:gt.metaitem.01:5933>;
var crushedGold             = <gregtech:gt.metaitem.01:5086>;	
var crushedGraphite	        = <gregtech:gt.metaitem.01:5865>;
var crushedGreenSapphire    = <gregtech:gt.metaitem.01:5504>;	
var crushedGrossular	    = <gregtech:gt.metaitem.01:5831>;
var crushedIlmenite         = <gregtech:gt.metaitem.01:5918>;	
var crushedIridium          = <gregtech:gt.metaitem.01:5084>;	
var crushedIron             = <gregtech:gt.metaitem.01:5032>;	
var crushedLapis            = <gregtech:gt.metaitem.01:5526>;	
var crushedLazurite	        = <gregtech:gt.metaitem.01:5524>;
var crushedLead             = <gregtech:gt.metaitem.01:5089>;	
var crushedLepidolite	    = <gregtech:gt.metaitem.01:5907>;
var crushedLignite	        = <gregtech:gt.metaitem.01:5538>;
var crushedLithium	        = <gregtech:gt.metaitem.01:5006>;
var crushedMagnesite	    = <gregtech:gt.metaitem.01:5908>;
var crushedMagnetite	    = <gregtech:gt.metaitem.01:5870>;
var crushedMalachite	    = <gregtech:gt.metaitem.01:5871>;
var crushedManganese        = <gregtech:gt.metaitem.01:5031>;	
var crushedMeteoricIron	    = <gregtech:gt.metaitem.01:5340>;
var crushedMolybdenite	    = <gregtech:gt.metaitem.01:5942>;
var crushedMolybdenum	    = <gregtech:gt.metaitem.01:5048>;
var crushedMonazite	        = <gregtech:gt.metaitem.01:5520>;
var crushedNaquadah         = <gregtech:gt.metaitem.01:5324>;	
var crushedNaquadria	    = <gregtech:gt.metaitem.01:5327>;
var crushedNeodymium	    = <gregtech:gt.metaitem.01:5067>;
var crushedNickel           = <gregtech:gt.metaitem.01:5034>;	
var crushedOilsands	        = <gregtech:gt.metaitem.01:5878>;
var crushedOlivine          = <gregtech:gt.metaitem.01:5505>;	
var crushedOsmium	        = <gregtech:gt.metaitem.01:5083>;
var crushedPalladium	    = <gregtech:gt.metaitem.01:5052>;
var crushedPentlandite	    = <gregtech:gt.metaitem.01:5909>;
var crushedPhosphate	    = <gregtech:gt.metaitem.01:5833>;
var crushedPhosphorus	    = <gregtech:gt.metaitem.01:5534>;
var crushedPitchblende	    = <gregtech:gt.metaitem.01:5873>;
var crushedPlatinum         = <gregtech:gt.metaitem.01:5085>;	
var crushedPlutonium        = <gregtech:gt.metaitem.01:5100>;	
var crushedPowellite	    = <gregtech:gt.metaitem.01:5883>;
var crushedPyrite	        = <gregtech:gt.metaitem.01:5834>;
var crushedPyrolusite	    = <gregtech:gt.metaitem.01:5943>;
var crushedPyrope	        = <gregtech:gt.metaitem.01:5835>;
var crushedQuartzite	    = <gregtech:gt.metaitem.01:5523>;
var crushedRedstone         = <gregtech:gt.metaitem.01:5810>;	
var crushedRockSalt	        = <gregtech:gt.metaitem.01:5944>;
var crushedRuby             = <gregtech:gt.metaitem.01:5502>;	
var crushedSalt	            = <gregtech:gt.metaitem.01:5817>;
var crushedSapphire         = <gregtech:gt.metaitem.01:5503>;	
var crushedScheelite	    = <gregtech:gt.metaitem.01:5910>;
var crushedSheldonite	    = <gregtech:gt.metaitem.01:5828>;
var crushedSilver           = <gregtech:gt.metaitem.01:5054>;	
var crushedSoapstone	    = <gregtech:gt.metaitem.01:5877>;
var crushedSodalite	        = <gregtech:gt.metaitem.01:5525>;
var crushedSpessartine	    = <gregtech:gt.metaitem.01:5838>;
var crushedSphalerite	    = <gregtech:gt.metaitem.01:5839>;
var crushedSpodumene	    = <gregtech:gt.metaitem.01:5920>;
var crushedStibnite	        = <gregtech:gt.metaitem.01:5945>;
var crushedSulfur	        = <gregtech:gt.metaitem.01:5022>;
var crushedTalc	            = <gregtech:gt.metaitem.01:5902>;
var crushedTantalite	    = <gregtech:gt.metaitem.01:5921>;
var crushedTetrahedrite	    = <gregtech:gt.metaitem.01:5840>;
var crushedThorium	        = <gregtech:gt.metaitem.01:5096>;
var crushedTin              = <gregtech:gt.metaitem.01:5057>;	
var crushedTitanium	        = <gregtech:gt.metaitem.01:5028>;
var crushedTungstate        = <gregtech:gt.metaitem.01:5841>;	
var crushedUraninite	    = <gregtech:gt.metaitem.01:5922>;
var crushedUranium235	    = <gregtech:gt.metaitem.01:5097>;
var crushedUranium238       = <gregtech:gt.metaitem.01:5098>;	
var crushedVanMagnetite	    = <gregtech:gt.metaitem.01:5923>;
var crushedWulfenite	    = <gregtech:gt.metaitem.01:5882>;
var crushedYLimonite	    = <gregtech:gt.metaitem.01:5931>;
var crushedZinc             = <gregtech:gt.metaitem.01:5036>;	


# Multiplication (Chemical Reactor)
//OutputStack, OutputFluid, InputStack1, InputStack2, InputFluid, Time in Ticks
//ChemicalReactor.addRecipe(Purified * 4, Liquid Byproduct * 144, Comb * 9, Crushed, <liquid:water> * 1000, 96);
ChemicalReactor.addRecipe(null, moltenIron * 144, combSteel * 9, crushedMagnetite, water * 1000, 96);
ChemicalReactor.addRecipe(null, moltenIron * 144, combSteel * 9, crushedMeteoricIron, water * 1000, 96);
ChemicalReactor.addRecipe(null, moltenNickel * 144, combSteel * 9, crushedIron, water * 1000, 96);
ChemicalReactor.addRecipe(null, moltenNickel * 144, combSteel * 9, crushedYLimonite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedAlmandine * 4, null, combSapphire * 9, crushedAlmandine, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedAluminium * 4, null, combAluminium * 9, crushedAluminium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedApatite * 4, null, combStone * 9, crushedApatite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBandedIron * 4, null, combIron * 9, crushedBandedIron, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBarite * 4, null, combCertus * 9, crushedBarite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBastnasite * 4, moltenNeodymium * 144, combChrome * 9, crushedBastnasite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBauxite * 4, null, combGold * 9, crushedBauxite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBauxite * 4, null, combTitanium * 9, crushedBauxite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBentonite * 4, moltenAluminium * 144, combOlivine * 9, crushedBentonite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBeryllium * 4, null, combEmerald * 9, crushedBeryllium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedBLimonite * 4, null, combIron * 9, crushedBLimonite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCalcite * 4, null, combLapis * 9, crushedCalcite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCassiterite * 4, moltenTin * 144, combTin * 9, crushedCassiterite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCertus * 4, null, combCertus * 9, crushedCertus, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedChalcopyrite * 4, null, combCopper * 9, crushedChalcopyrite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedChrome * 4, moltenIron * 144, combChrome * 9, crushedChrome, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedChromite * 4, moltenIron * 144, combChrome * 9, crushedChromite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCinnabar * 4, moltenRedstone * 144, combRedstone * 9, crushedCinnabar, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCoal * 4, null, combCoal * 9, crushedCoal, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCobaltite * 4, moltenCobalt * 144, combNickel * 9, crushedCobaltite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedCopper * 4, moltenCobalt * 144, combCopper * 9, crushedCopper, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedDiamond * 4, null, combDiamond * 9, crushedDiamond, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedEmerald * 4, moltenBeryllium * 144, combEmerald * 9, crushedEmerald, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedEnrichedNaq * 4, moltenNaquadah, combNaquadah * 9, crushedEnrichedNaq, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGalena * 4, null, combLead * 9, crushedGalena, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGalena * 4, null, combSilver * 9, crushedGalena, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGarnierite * 4, moltenNickel * 144, combNickel * 9, crushedGarnierite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGlauconite * 4, null, combOlivine * 9, crushedGlauconite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGold * 4, moltenCopper * 144, combGold * 9, crushedGold, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGold * 4, moltenIron * 144, combGold * 9, crushedGold, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGraphite * 4, moltenCarbon * 144, combDiamond * 9, crushedGraphite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGreenSapphire * 4, moltenAluminium * 144, combSapphire * 9, crushedGreenSapphire, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedGrossular * 4, null, combManganese * 9, crushedGrossular, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedIlmenite * 4, moltenIron * 144, combTitanium * 9, crushedIlmenite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedIridium * 4, moltenPlatinum * 144, combIridium * 9, crushedIridium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedIron * 4, moltenNickel * 144, combIron * 9, crushedIron, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLapis * 4, null, combLapis * 9, crushedLapis, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLazurite * 4, null, combLapis * 9, crushedLazurite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLead * 4, moltenSilver * 144, combLead * 9, crushedLead, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLepidolite * 4, moltenLithium * 144, combSlag * 9, crushedLepidolite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLignite * 4, null, combLignite * 9, crushedLignite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedLithium * 4, moltenLithium * 144, combTungsten * 9, crushedLithium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMagnesite * 4, moltenMagnesium * 144, combOlivine * 9, crushedMagnesite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMagnetite * 4, moltenIron * 144, combIron * 9, crushedMagnetite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMalachite * 4, moltenCopper * 144, combCopper * 9, crushedMalachite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedManganese * 4, moltenChrome * 144, combManganese * 9, crushedManganese, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMeteoricIron * 4, moltenIron * 144, combIron * 9, crushedMeteoricIron, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMolybdenite * 4, moltenMolybdenum * 144, combSteel * 9, crushedMolybdenite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMolybdenum * 4, null, combSteel * 9, crushedMolybdenum, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedMonazite * 4, moltenThorium * 144, combSlag * 9, crushedMonazite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedNaquadah * 4, moltenNaquadahEnriched * 144, combNaquadah * 9, crushedNaquadah, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedNaquadria * 4, null, combNaquadah * 9, crushedNaquadria, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedNeodymium * 4, null, combChrome * 9, crushedNeodymium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedNickel * 4, moltenCobalt * 144, combNickel * 9, crushedNickel, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedOilsands * 4, null, combOil * 9, crushedOilsands, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedOlivine * 4, null, combOlivine * 9, crushedOlivine, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedOsmium * 4, moltenIridium * 144, combIridium * 9, crushedOsmium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPalladium * 4, null, combPlatinum * 9, crushedPalladium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPentlandite * 4, moltenIron * 144, combNickel * 9, crushedPentlandite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPhosphate * 4, null, combStone * 9, crushedPhosphate, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPhosphorus * 4, null, combStone * 9, crushedPhosphorus, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPitchblende * 4, moltenThorium * 144, combUranium238 * 9, crushedPitchblende, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPlatinum * 4, moltenNickel * 144, combPlatinum * 9, crushedPlatinum, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPlutonium * 4, moltenUranium238 * 144, combPlutonium * 9, crushedPlutonium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPlutonium * 4, null, combPlutonium * 9, crushedUranium235, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPowellite * 4, null, combNickel * 9, crushedPowellite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPyrite * 4, null, combCopper * 9, crushedPyrite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPyrite * 4, null, combIron * 9, crushedPyrite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPyrolusite * 4, moltenManganese * 144, combManganese * 9, crushedPyrolusite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedPyrope * 4, null, combSapphire * 9, crushedPyrope, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedQuartzite * 4, null, combCertus * 9, crushedQuartzite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRedstone * 4, null, combChrome * 9, crushedRedstone, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRedstone * 4, null, combRedstone * 9, crushedRedstone, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRedstone * 4, null, combRuby * 9, crushedRedstone, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRockSalt * 4, null, combSlag * 9, crushedRockSalt, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRuby * 4, moltenChrome * 144, combChrome * 9, crushedRuby, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedRuby * 4, moltenChrome * 144, combRuby * 9, crushedRuby, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSalt * 4, null, combSlag * 9, crushedSalt, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSapphire * 4, moltenAluminium * 144, combSapphire * 9, crushedSapphire, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedScheelite * 4, moltenManganese * 144, combTungsten * 9, crushedScheelite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSheldonite * 4, moltenPalladium * 144, combPlatinum * 9, crushedSheldonite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSilver * 4, moltenLead * 144, combSilver * 9, crushedSilver, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSoapstone * 4, null, combStone * 9, crushedSoapstone, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSodalite * 4, null, combLapis * 9, crushedSodalite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSpessartine * 4, null, combManganese * 9, crushedSpessartine, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSphalerite * 4, null, combZinc * 9, crushedSphalerite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSpodumene * 4, moltenAluminium * 144, combSlag * 9, crushedSpodumene, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedStibnite * 4, moltenAntimony * 144, combCopper * 9, crushedStibnite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedSulfur * 4, null, combZinc * 9, crushedSulfur, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTalc * 4, null, combStone * 9, crushedTalc, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTantalite * 4, moltenManganese * 144, combManganese * 9, crushedTantalite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTetrahedrite * 4, moltenAntimony * 144, combCopper * 9, crushedTetrahedrite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedThorium * 4, moltenUranium238 * 144, combEmerald * 9, crushedThorium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTin * 4, moltenIron * 144, combTin * 9, crushedTin, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTitanium * 4, null, combTitanium * 9, crushedTitanium, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedTungstate * 4, moltenManganese * 144, combTungsten * 9, crushedTungstate, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedUraninite * 4, moltenUranium238 * 144, combUranium238 * 9, crushedUraninite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedUranium235 * 4, null, combUranium238 * 9, crushedUranium235, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedUranium238 * 4, moltenLead * 144, combUranium238 * 9, crushedUranium238, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedVanMagnetite * 4, null, combIron * 9, crushedVanMagnetite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedWulfenite * 4, null, combNickel * 9, crushedWulfenite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedYLimonite * 4, moltenNickel * 144, combIron * 9, crushedYLimonite, water * 1000, 96);
ChemicalReactor.addRecipe(purifiedZinc * 4, moltenTin * 144, combZinc * 9, crushedZinc, water * 1000, 96);


# Autoclaving
//OutputStack, InputStack, InputFluid, OutputStackChance, Time in Ticks, EnergyUsage
//Autoclave.addRecipe(Purified ore, Comb * 16, <liquid:UUM> * 1, 1000, 1000, 24);
Autoclave.addRecipe(purifiedAluminium, combAluminium * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedCertus, combCertus * 16, UUM * 10, 10000, 1000, 24);
Autoclave.addRecipe(purifiedChrome, combChrome * 16, UUM * 6, 10000, 1000, 24);
Autoclave.addRecipe(purifiedCoal, combCoal * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedCopper, combCopper * 16, UUM * 7, 10000, 1000, 24);
Autoclave.addRecipe(purifiedDiamond, combDiamond * 16, UUM * 77, 10000, 1000, 24);
Autoclave.addRecipe(purifiedEmerald, combEmerald * 16, UUM * 2, 10000, 1000, 24);
Autoclave.addRecipe(purifiedGold, combGold * 16, UUM * 20, 10000, 1000, 24);
Autoclave.addRecipe(purifiedIridium, combIridium * 16, UUM * 20, 10000, 1000, 24);
Autoclave.addRecipe(purifiedIron, combIron * 16, UUM * 6, 10000, 1000, 24);
Autoclave.addRecipe(purifiedLapis, combLapis * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedLead, combLead * 16, UUM * 21, 10000, 1000, 24);
Autoclave.addRecipe(purifiedLignite, combLignite * 16, UUM * 1, 10000, 1000, 24);
Autoclave.addRecipe(purifiedManganese, combManganese * 16, UUM * 6, 10000, 1000, 24);
Autoclave.addRecipe(purifiedMolybdenite, combSteel * 16, UUM * 6, 10000, 1000, 24);
Autoclave.addRecipe(purifiedNaquadah, combNaquadah * 16, UUM * 10, 10000, 1000, 24);
Autoclave.addRecipe(purifiedNickel, combNickel * 16, UUM * 6, 10000, 1000, 24);
Autoclave.addRecipe(purifiedOilsands, combOil * 16, UUM * 10, 10000, 1000, 24);
Autoclave.addRecipe(purifiedOlivine, combOlivine * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedPlatinum, combPlatinum * 16, UUM * 20, 10000, 1000, 24);
Autoclave.addRecipe(purifiedPlutonium, combPlutonium * 16, UUM * 25, 10000, 1000, 24);
Autoclave.addRecipe(purifiedRedstone, combRedstone * 16, UUM * 9, 10000, 1000, 24);
Autoclave.addRecipe(purifiedRuby, combRuby * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedSalt, combSlag * 16, UUM * 3, 10000, 1000, 24);
Autoclave.addRecipe(purifiedSapphire, combSapphire * 16, UUM * 2, 10000, 1000, 24);
Autoclave.addRecipe(purifiedSilver, combSilver * 16, UUM * 11, 10000, 1000, 24);
Autoclave.addRecipe(purifiedSoapstone, combStone * 16, UUM * 2, 10000, 1000, 24);
Autoclave.addRecipe(purifiedTin, combTin * 16, UUM * 12, 1000, 10000, 24);
Autoclave.addRecipe(purifiedTitanium, combTitanium * 16, UUM * 5, 10000, 1000, 24);
Autoclave.addRecipe(purifiedTungstate, combTungsten * 16, UUM * 4, 10000, 1000, 24);
Autoclave.addRecipe(purifiedUranium238, combUranium238 * 16, UUM * 24, 10000, 1000, 24);
Autoclave.addRecipe(purifiedZinc, combZinc * 16, UUM * 7, 10000, 1000, 24);
